### ISSUE TITLE
Python3のテストを導入します。

### ISSUE THREAD

**Issue by solWat** [kwacgit/kazy-english-class-notify#22]
unittestがシンプルで良いのではないでしょうか。
https://blog.amedama.jp/entry/python-unittest

どうせなら、dockerのことも考慮した構成にしましょう。
https://www.rhoboro.com/2018/09/07/docker-exclude-tests.html

**Comment by solWat** [comment]
またまた、どうせなら、後でpytestに移行することも考えたディレクトリ構成にしとくのがベターかもしれません。

https://blog.amedama.jp/entry/python-unittest
の「一般的な pytest のディレクトリ構成」を参考に。

**Comment by KAZYPinkSaurus** [comment]
>どうせなら、dockerのことも考慮した構成にしましょう。
https://www.rhoboro.com/2018/09/07/docker-exclude-tests.html

に関連して
.dockerignoreを使用することでビルド時間が遅くなるケースも有るようですね｡(使うことを否定しているわけではありません｡ testコードは運用時は不要だと私も思います)
https://qiita.com/munisystem/items/b0f08b28e8cc26132212

**Comment by solWat** [comment]
記事の共有ありがとうございます。
このリポジトリに関しては、そこまで巨大なプロジェクトにはならないと思うので、無視して進めてください。

**Comment by KAZYPinkSaurus** [comment]
テストをするためにnotify.py内の関数を増やす｡
