### ISSUE TITLE
dockerfileを空のディレクトリに置くようにします。

### ISSUE THREAD

**Issue by solWat** [kwacgit/kazy-english-class-notify#25]
dockerfileのベストプラクティスに則って、空のディレクトリに置きます。
http://docs.docker.jp/engine/articles/dockerfile_best-practice.html#dockerignore

今後、DBコンテナ用のdockerfileなどが増えてくると思うので、将来を想定したディレクトリ構成を考えます。

**Comment by KAZYPinkSaurus** [comment]
こんなイメージかな?
```
dockerfiles
├── app
│   └── Dockerfile
└── db
    └── Dockerfile
```

**Comment by solWat** [comment]
良いと思います。
なんか他のOSSだとこういう構成にしてる、みたいなところまで調べたいね。

**Comment by solWat** [comment]
https://qiita.com/enta0701/items/b872eef6d910908c0e6c#13-%E8%A4%87%E6%95%B0%E3%81%AEdockerfile%E3%82%92%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AB%E5%90%AB%E3%82%81%E3%82%8B
を参考にすると、以下のような形。`.docker`を隠しファイルにしてるのがちょっと気になる。
一応、それぞれにREADME.mdを入れよう。
https://qiita.com/suecharo/items/a5e0cd3fe6d31443c536#github-側の設定
```
.docker
└── containers
    ├── app
    │   └── Dockerfile
    │   └── README.md
    └── db
        └── Dockerfile
        └── README.md
```
