### ISSUE TITLE
サービスとして公開していいのか調査

### ISSUE THREAD

**Issue by KAZYPinkSaurus** [kwacgit/kazy-english-class-notify#29]
ちゃんと考えないと🚓👮‍♀️

**Comment by solWat** [comment]
将来的に、ユーザの入力してもらったID／PWを利用するような機能をつけたとしても、
ソースも公開してるから問題なさそうな気がするけどなあ。。。
どうなんだろ。

**Comment by KAZYPinkSaurus** [comment]
他サイトから情報まとめてサービスにしているなんてよくある話だから大丈夫化

**Comment by KAZYPinkSaurus** [comment]
利用規約の禁止事項
>本サービスの運用を妨げる行為
本サービスを営業行為、営利目的及びその準備に利用する行為

https://eikaiwa.dmm.com/terms_of_use/

**Comment by solWat** [comment]
お金とっちゃダメってことかね

**Comment by KAZYPinkSaurus** [comment]
そんな感じがするね

**Comment by solWat** [comment]
本ツール・サービスの利用には、お金を取らないということで、FA。
